# $1 for ip
# $2 for port
# $3 for pairing code
# $4 for adress
export ANDROID_HOME="/data/data/com.termux/files/usr/share/android-sdk/"
unzip wwwfactory.zip
cd wwwfactory
echo "package com.wwwfactory

import android.net.Uri
import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import androidx.browser.customtabs.CustomTabsIntent
import kotlin.system.exitProcess

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val builder = CustomTabsIntent.Builder()
        builder.setInstantAppsEnabled(true)
        val customBuilder = builder.build()
        customBuilder.intent.setPackage('com.android.chrome')
        customBuilder.launchUrl(this, Uri.parse('$4'))
    }

    override fun onWindowFocusChanged(hasFocus: Boolean) {
        super.onWindowFocusChanged(hasFocus)
        finishAndRemoveTask();
    }

}" > app/src/main/java/com/wwwfactory/MainActivity.kt
echo "## This file is automatically generated by Android Studio.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file should *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
sdk.dir=$ANDROID_HOME" > local.properties
adb pair "$1:$2 $3"
./gradlew build
./gradlew installDebug
